logging:
  level: INFO
  loggers:
    com.spotler: DEBUG
server:
  applicationConnectors:
    - type: http
      port: 9026
  adminConnectors:
    - type: http
      port: 9027
database:
  driverClass: org.mariadb.jdbc.Driver
  user: export
  password: changeMe
  url: jdbc:mariadb://localhost:3306/ExportService
  checkConnectionWhileIdle: true
  properties:
    charSet: UTF-8
    useSSL: false
  maxWaitForConnection: 10s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  initialSize: 0
  minSize: 0
  maxSize: 10
  evictionInterval: 10s
  minIdleTime: 1 minute
accountManagementUrl: https://sso.spotler.test/
dataLake:
  sftpHost: ftp.spotler.co.uk
  sftpUsername: productdatasftp
  sftpPassword: changeMe
  maxRetries: 1
mailPlus:
  consumerKey: hkljiyuhljklkyug237y9gkjl2
  consumerSecret: 435hjkgef790543bjklefrwg97u
  timeout: 60000